reshape() — Changing shape of array


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 5,34])
reshaped = a.reshape(4,2)
print(reshaped)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 5 34]]


flatten() — Make multidimensional to 1D

In [ ]:
arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()
print(flat)


[1 2 3 4]


axis in operations (important!)

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.sum(a, axis=0))  # sum column-wise: [4, 6]
print(np.sum(a, axis=1))  # sum row-wise: [3, 7]

[4 6]
[3 7]


np.where() — condition-based output

In [ ]:
a = np.array([10, 15, 20, 25])
result = np.where(a > 18, 'High', 'Low')
print(result)


['Low' 'Low' 'High' 'High']


np.unique() — Find unique values

In [ ]:
a = np.array([1, 2, 2, 3, 3, 3,7,54,3,3,545,4,6,4577,5,7])
print(np.unique(a))


[   1    2    3    4    5    6    7   54  545 4577]


np.concatenate() — Join arrays

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
joined = np.concatenate((a, b))
print(joined)


[1 2 3 4]


np.random Module (for ML use)

In [ ]:
print(np.random.randint(1, 10, size=(2, 3)))  # random integers 1–9
print(np.random.rand(2, 2))                  # random floats 0–1


[[8 6 8]
 [3 7 8]]
[[0.37923722 0.41611843]
 [0.03476667 0.41054516]]


np.linspace() — evenly spaced numbers

In [ ]:
print(np.linspace(0, 1, 5))  # 5 numbers between 0 and 1


[0.   0.25 0.5  0.75 1.  ]


Boolean Indexing (filtering)

In [ ]:
a = np.array([10, 20, 30, 40])
print(a[a > 20])  # filter elements greater than 20


[30 40]


np.argmax() & np.argmin() — index of max/min



In [ ]:
a = np.array([10, 50, 30])
print(np.argmax(a))  # index of max (1)
print(np.argmin(a))  # index of min (0)

1
0
